CREATE TABLE citacoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  texto TEXT NOT NULL,
  bg VARCHAR(255) DEFAULT 'bg-white/60',
  text_col VARCHAR(255) DEFAULT 'text-brand-dark',
  border VARCHAR(255) DEFAULT 'border-brand-red',
  quote_mark VARCHAR(255) DEFAULT 'text-brand-dark/10'
);

INSERT INTO citacoes (texto, bg, text_col, border, quote_mark) VALUES 
('O rigor científico é a bússola que orienta a excelência na estratégia tributária.', 'bg-white/60', 'text-brand-dark', 'border-brand-red', 'text-brand-dark/10'),
('A governança não é apenas um selo, é o alicerce para negócios duradouros.', 'bg-brand-dark/90', 'text-white', 'border-[#E5E5E5]', 'text-white/10'),
('Desenvolver soluções exige integrar eficiência fiscal e responsabilidade sustentável.', 'bg-brand-red/90', 'text-white', 'border-brand-dark', 'text-brand-dark/20'),
('O debate acadêmico oxigena e impulsiona as transformações do setor produtivo.', 'bg-[#EFECE8]/90', 'text-brand-dark', 'border-brand-dark', 'text-brand-dark/10');
